# Generated by Django 2.2 on 2022-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='items',
            field=models.ManyToManyField(blank=True, to='item.Item'),
        ),
    ]
