# Generated by Django 2.2 on 2022-08-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20220804_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='items',
        ),
    ]
