# Generated by Django 2.2 on 2022-08-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_remove_budget_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='currency',
            field=models.CharField(choices=[('N', 'Naira'), ('$', 'US Dollar')], default='N', max_length=1),
        ),
    ]
