# Generated by Django 2.2 on 2022-06-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=0, upload_to='items'),
            preserve_default=False,
        ),
    ]
