# Generated by Django 2.2 on 2022-06-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
