# Generated by Django 2.2 on 2022-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20220608_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.ManyToManyField(blank=True, to='item.Comment'),
        ),
    ]
