# Generated by Django 2.2 on 2022-08-04 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_remove_budget_items'),
        ('item', '0007_auto_20220615_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='budget',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budget.Budget'),
            preserve_default=False,
        ),
    ]
