# Generated by Django 2.2 on 2022-08-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_item_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
    ]
