# Generated by Django 2.2 on 2022-06-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0003_friendshiprequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='accepted',
        ),
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('PN', 'PENDING'), ('RE', 'REJECTED'), ('AC', 'ACCEPTED')], default='PENDING', max_length=50),
        ),
        migrations.DeleteModel(
            name='FriendshipRequest',
        ),
    ]
