# Generated by Django 2.2 on 2022-06-13 12:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='target_user',
        ),
        migrations.AddField(
            model_name='share',
            name='target_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
