# Generated by Django 2.2 on 2022-07-30 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_auto_20220613_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing', to='item.Item'),
        ),
    ]
