# Generated by Django 2.2 on 2022-07-30 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_auto_20220730_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item'),
        ),
    ]
