# Generated by Django 2.2 on 2022-08-05 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sharing', '0004_auto_20220730_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='item',
        ),
        migrations.AddField(
            model_name='share',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
